const cartActionTypes = {
  SET_CART_ITEMS: "SET_CART_ITEMS",
  SEND_TO_API_START: "SEND_TO_API_START",
  SEND_TO_API_SUCCESS: "SEND_TO_API_SUCCESS",
  SEND_TO_API_FAIL: "SEND_TO_API_FAIL",
  SET_RES_FROM_CHECKOUT: "SET_RES_FROM_CHECKOUT",
  START_PROCESS_PAYMENT: "START_PROCESS_PAYMENT",
};

export default cartActionTypes;
